apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "devsu-static-ip"
    networking.gke.io/managed-certificates: "devsu-managed-cert"
spec:
  rules:
  - host: gissepa.space
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: devsu-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirector-service
            port:
              number: 80
  - host: www.gissepa.space
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: devsu-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirector-service
            port:
              number: 80
